# This controller is REQUIRED for ros_control and MoveIt to know the robot's state
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  joints:
    - left_arm_joint1
    - left_arm_joint2
    - left_arm_joint3
    - left_arm_joint4
    - left_arm_joint5
    - left_arm_joint6
    - left_arm_joint7
    - left_arm_gripper_joint1
    - right_arm_joint1
    - right_arm_joint2
    - right_arm_joint3
    - right_arm_joint4
    - right_arm_joint5
    - right_arm_joint6
    - right_arm_joint7
    - right_arm_gripper_joint1

# MoveIt-generated controllers, MODIFIED for a position-based hardware interface
left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_arm_joint1
    - left_arm_joint2
    - left_arm_joint3
    - left_arm_joint4
    - left_arm_joint5
    - left_arm_joint6
    - left_arm_joint7

right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_arm_joint1
    - right_arm_joint2
    - right_arm_joint3
    - right_arm_joint4
    - right_arm_joint5
    - right_arm_joint6
    - right_arm_joint7

# Note: You typically don't run both "left_arm_controller" and "both_arms_controller"
# at the same time as they control the same joints. We define it here for flexibility.
both_arms_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_arm_joint1
    - left_arm_joint2
    - left_arm_joint3
    - left_arm_joint4
    - left_arm_joint5
    - left_arm_joint6
    - left_arm_joint7
    - right_arm_joint1
    - right_arm_joint2
    - right_arm_joint3
    - right_arm_joint4
    - right_arm_joint5
    - right_arm_joint6
    - right_arm_joint7

left_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_arm_gripper_joint1

right_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_arm_gripper_joint1